//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Estudiante
    {
        [Required(ErrorMessage = "Introduzca un ID valido.")]
        [DisplayName("ID")]
        public string id_student { get; set; }
        [Required(ErrorMessage ="Introduzca el nombre")]
        [DisplayName("Nombres")]

        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "El nombre debe contener solo letras.")]
        public string Nombres_estudiante { get; set; }
        [Required(ErrorMessage ="Introduzca el apellido")]
        [DisplayName("Apellidos")]

        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "El apellido debe contener solo letras.")]
        public string Apellidos_estudiante { get; set; }
        [Required(ErrorMessage = "Inserte un pais.")]
        [DisplayName("Pais")]

        public string Pais_estudiante { get; set; }

        [Required(ErrorMessage ="Introduzca el Email")]
        [DisplayName("E-mail")]

        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "El correo electrónico no es válido.")]
        public string Email_estudiante { get; set; }
        [Required(ErrorMessage = "Introduzca la contraseña")]
        [DisplayName("Password")]

        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$", ErrorMessage = "La contraseña no cumple con los requisitos, debe de tener mínimo 8 caracteres, al menos una letra minúscula, una letra mayúscula y un número.")]
        public string Password_estudiante { get; set; }

        [Required(ErrorMessage ="Introduzca el telefono")]
        [DisplayName("Tel")]

        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "El número de teléfono no es válido.")]
        public string Telefono_estudiante { get; set; }
    }
}
