//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projecto1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Materias
    {
        [Required(ErrorMessage ="Introduzca un ID Valido")]
        [DisplayName("ID")]
        public string id_materia { get; set; }

        [Required(ErrorMessage = "Introduzca el nombre")]
        [DisplayName("Nombres")]

        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "El nombre debe contener solo letras.")]
        public string Nombres_estudiante { get; set; }
        [Required(ErrorMessage = "Introduzca el nombre")]
        [DisplayName("Nombres")]

        [RegularExpression(@"^[A-Za-z\s]+$", ErrorMessage = "El apellido debe contener solo letras.")]
        public string Apellidos_estudiante { get; set; }

        [Required(ErrorMessage = "Introduzca una materia")]
        [DisplayName("Materia")]
        public string Materia { get; set; }

        [Required(ErrorMessage = "Introduzca un horario")]
        [DisplayName("Horario")]
        public string Hora { get; set; }

        [Required(ErrorMessage = "Confirme el Email")]
        [DisplayName("E-mail")]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", ErrorMessage = "El correo electrónico no es válido.")]
        public string Email_estudiante { get; set; }
    }
}
